name: TorneoMMT
version: 1.0-SNAPSHOT
main: los5fantasticos.torneo.TorneoPlugin
api-version: 1.20
description: Sistema de torneo de Minecraft con múltiples minijuegos y ranking global
authors: [Los5Fantasticos]

commands:
  # Comandos del Core
  ranking:
    description: Muestra el ranking global del torneo
    usage: /<command>
    aliases: [rank, top]
  
  torneo:
    description: Alias para el comando ranking
    usage: /<command>
  
  # Comandos de Minijuegos
  memorias:
    description: Comandos del minijuego Memorias
    usage: /<command> [setup|start|stop|size]
    permission: torneo.admin
  
  robarcabeza:
    description: Comandos del minijuego Robar la Cabeza
    usage: /<command> [join|leave|admin]
    aliases: [rc]
  
  skywars:
    description: Comandos del minijuego SkyWars
    usage: /<command> [setup|start|stop]
    permission: torneo.admin
  
  laberinto:
    description: Comandos del minijuego Laberinto
    usage: /<command> [setup|start|stop]
  
  carrera:
    description: Comandos del minijuego Carrera de Barcos
    usage: /<command> [crear|setlobby|addspawn|addcheckpoint|setmeta|list|unirse|salir]
    aliases: [carrerabarcos]
  
  cadena:
    description: Comandos del minijuego Cadena (parkour cooperativo encadenado)
    usage: /<command> [join|admin]
    aliases: [chain]
  
  hungergames:
    description: Comandos del minijuego Hunger Games
    usage: /<command> [setup|start|stop]
    permission: torneo.admin
  
  coliseo:
    description: Comandos del minijuego Coliseo (Élite vs Horda)
    usage: /<command> [admin]
    permission: torneo.admin

permissions:
  torneo.admin:
    description: Permisos de administrador del torneo
    default: op
    children:
      torneo.play: true
      cadena.admin: true
      robarcabeza.admin: true
      coliseo.admin: true

  torneo.play:
    description: Permite jugar en los minijuegos del torneo
    default: true
  
  cadena.admin:
    description: Permite usar comandos de administración de Cadena
    default: op

  robarcabeza.admin:
    description: Permite usar comandos de administración de RobarCabeza
    default: op

  laberinto.admin:
    description: Permite usar comandos de administración de Laberinto
    default: op
